---

#
# Packages required for ansible to run
#
- name: install packages required for ansible
  yum: pkg={{ item }} state=installed
  with_items:
    - libselinux-python

#
# ntp and timezone
#

- name: set timezone
  template: src=clock.j2 dest=/etc/sysconfig/clock

#
# The file module refuses to create a link where a file exists, and
# initially the /etc/localtime file is a file. So had to fall back to
# using ln -sf, which is not good. Perhaps should be creating a file
# instead of a link here.
#

- name: setup timezone link
  shell: ln -sf /usr/share/zoneinfo/{{timezone_country}}/{{timezone_city}} /etc/localtime
  #file: state=link src=/usr/share/zoneinfo/{{timezone_country}}/{{timezone_city}} dest=/etc/localtime

- name: install ntp package
  yum: pkg=ntp state=installed

- name: check if ntp is syncronized
  shell: ntpstat
  register: ntp_syncronized
  ignore_errors: True
  changed_when: ntp_syncronized.rc > 0

- name: stop ntpd to run ntpdate
  service: name=ntpd state=stopped
  when: ntp_syncronized.rc > 0
  ignore_errors: True

- name: run ntpdate
  shell: ntpdate {{ ntpdate_timeserver }}
  when: ntp_syncronized.rc > 0

- name: ensure ntp service is running and enabled
  service: name=ntpd state=started enabled=yes

#
# I was trying to use ntpstat to check if time is syncronized, but
# even after time is setup Ok with ntpdate and ntpd is running, it
# still takes some time for the clock to line up properly. So this
# might not work, and have commented it out for now.
#

#- name: check if ntp is syncronized again
#  shell: ntpstat
#  when: ntp_syncronized.rc > 0

#
# Disable selinux
#

- name: disable selinux
  selinux: state=disabled

#
# Configure a custom repository 
#

- name: install serverascode centos 6 packagecloud repo
  copy: src=serverascode-centos6.repo dest=/etc/yum.repos.d/serverascode-centos6.repo owner=root group=root mode=0644
  notify:
    - refresh yum cache

# XXX This was not working? Problem with packagecloud?
#- name: import packagecloud gpg key
#  command: rpm --import https://packagecloud.io/gpg.key

#
# Install epel repository
#

- name: install epel repository rpm
  shell: rpm -ih http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  ignore_errors: True
  notify:
    - refresh yum cache

#
# Install rpmforge
#

- name: install rpmforge repository
  command: rpm -ih http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm creates=/etc/yum.repos.d/rpmforge.repo
  ignore_errors: True
  notify:
    - refresh yum cache

#
# Makecache
#

#- name: Makecache
#  command: yum makecache

#
# Iptables
#

- name: disable iptables
  service: name=iptables state=stopped enabled=no
